SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
    AND S.SALES_DATE >= DATE('2022-01-01') 
    AND S.SALES_DATE <= DATE('2022-01-31')
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY 1, 3 DESC;