-- 코드를 입력하세요
SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID)
FROM ONLINE_SALE S INNER JOIN USER_INFO U
ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER;