-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, 30 * C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE
AND C.CAR_TYPE IN ('SUV', '세단')
AND P.DURATION_TYPE IN ('30일 이상')
AND C.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
    OR TO_DATE('2022-11-30', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
)
AND (30 * C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, 2, 1 DESC;