-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS C
WHERE (SELECT LISTAGG(NAME)
      FROM CART_PRODUCTS
      WHERE CART_ID = C.CART_ID
      GROUP BY CART_ID) LIKE '%Milk%'
      AND (SELECT LISTAGG(NAME)
      FROM CART_PRODUCTS
      WHERE CART_ID = C.CART_ID
      GROUP BY CART_ID) LIKE '%Yogurt%'
GROUP BY CART_ID
ORDER BY CART_ID;