WITH BASE_TBL AS (
    SELECT ID, 
        CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END AS FISH_LENGTH
    FROM FISH_INFO
)
SELECT ROUND(AVG(FISH_LENGTH), 2) AS AVERAGE_LENGTH
FROM BASE_TBL;