WITH BASE_DATA AS (
    SELECT ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERC_RANK
    FROM ECOLI_DATA
)
SELECT ID,
    CASE 
        WHEN PERC_RANK <= 0.25 THEN 'CRITICAL'
        WHEN PERC_RANK <= 0.5 THEN 'HIGH'
        WHEN PERC_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM BASE_DATA
ORDER BY 1;