SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS, ANIMAL_OUTS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND LOWER(INS.SEX_UPON_INTAKE) LIKE ('%Intact%')
AND (LOWER(OUTS.SEX_UPON_OUTCOME) LIKE ('%Spayed%')
OR LOWER(OUTS.SEX_UPON_OUTCOME) LIKE ('%Neutered%'));