SELECT REST.REST_ID, 
    REST.REST_NAME, 
    REST.FOOD_TYPE, 
    REST.FAVORITES,
    REST.ADDRESS, 
    ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO REST INNER JOIN REST_REVIEW REVIEW
    ON REST.REST_ID = REVIEW.REST_ID
WHERE REST.ADDRESS LIKE ('서울%')
GROUP BY REST.REST_ID, REST.REST_NAME, REST.FOOD_TYPE, REST.FAVORITES, REST.ADDRESS
ORDER BY 6 DESC, 4 DESC
;