SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR, 
    DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
    GENDER, 
    COUNT(DISTINCT USER.USER_ID) AS USERS
FROM USER_INFO USER INNER JOIN ONLINE_SALE SALE
ON (USER.USER_ID = SALE.USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3;