-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                         FROM ANIMAL_OUTS
                         WHERE ANIMAL_ID = I.ANIMAL_ID)
ORDER BY I.DATETIME
FETCH FIRST 3 ROWS ONLY;