-- 코드를 입력하세요
WITH COUNT AS (SELECT MEMBER_ID, COUNT(*) 
               FROM REST_REVIEW
               GROUP BY MEMBER_ID
               ORDER BY COUNT(*) DESC
               FETCH FIRST 1 ROW ONLY)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT MEMBER_ID FROM COUNT)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;