WITH TMP AS (
    SELECT ID,
        CASE
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('01', '02', '03') THEN '1Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('04', '05', '06') THEN '2Q'
            WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m') IN ('07', '08', '09') THEN '3Q'
            ELSE '4Q'
        END AS 'QUARTER'
    FROM ECOLI_DATA
)
SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA INNER JOIN TMP USING (ID)
GROUP BY QUARTER
ORDER BY 1;