-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(SALES)
FROM BOOK B JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE SUBSTR(TO_CHAR(S.SALES_DATE, 'YYYY-MM-DD'), 1, 7) = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;