-- 코드를 입력하세요
SELECT HISTORY_ID, DAILY_FEE * DURATION * (100 - NVL(DISCOUNT_RATE, 0)) / 100 AS FEE
FROM (
        SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, END_DATE - START_DATE + 1 AS DURATION,
            CASE WHEN END_DATE - START_DATE >= 90 THEN 90
                 WHEN END_DATE - START_DATE >= 30 THEN 30
                 WHEN END_DATE - START_DATE >= 7 THEN 7
                 ELSE 0
            END || '일 이상' AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            LEFT JOIN CAR_RENTAL_COMPANY_CAR C
        USING(CAR_ID)
        WHERE CAR_TYPE = '트럭'
) C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    USING(CAR_TYPE, DURATION_TYPE)
ORDER BY 2 DESC, 1 DESC;