-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r
ON (b.BOARD_ID = r.BOARD_ID)
WHERE TO_CHAR(b.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY r.CREATED_DATE, b.TITLE;