SELECT EMP.EMP_NO, EMP.EMP_NAME, 
    CASE
        WHEN AVG(GRADE.SCORE) >= 96 THEN 'S'
        WHEN AVG(GRADE.SCORE) >= 90 THEN 'A'
        WHEN AVG(GRADE.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN AVG(GRADE.SCORE) >= 96 THEN EMP.SAL * 0.2
        WHEN AVG(GRADE.SCORE) >= 90 THEN EMP.SAL * 0.15
        WHEN AVG(GRADE.SCORE) >= 80 THEN EMP.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES EMP, HR_GRADE GRADE
WHERE EMP.EMP_NO = GRADE.EMP_NO
GROUP BY EMP.EMP_NO, EMP.EMP_NAME
ORDER BY 1;