WITH BASE_TABLE AS (
    SELECT CAR_ID, COUNT(HISTORY_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT DATE_FORMAT(START_DATE, '%c') AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM BASE_TABLE)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY DATE_FORMAT(START_DATE, '%m'), 2 DESC;