WITH BASE_TBL AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT B.YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A, BASE_TBL B
WHERE YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2;