WITH BASE_TBL AS (
    SELECT F.FISH_TYPE, MAX(F.LENGTH) AS LENGTH
    FROM FISH_INFO F INNER JOIN FISH_NAME_INFO N USING (FISH_TYPE)
    GROUP BY F.FISH_TYPE
)
SELECT F.ID, I.FISH_NAME, F.LENGTH
FROM FISH_INFO F INNER JOIN FISH_NAME_INFO I USING (FISH_TYPE)
WHERE (F.FISH_TYPE, F.LENGTH) IN (SELECT * FROM BASE_TBL)
ORDER BY 1;