WITH TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT TOTAL.SCORE, EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_EMPLOYEES EMP 
    INNER JOIN TOTAL_SCORE TOTAL USING (EMP_NO)
WHERE TOTAL.SCORE = (SELECT MAX(SCORE) FROM TOTAL_SCORE);