SELECT B.CATEGORY, SUM(BS.SALES)
FROM BOOK B, BOOK_SALES BS
WHERE B.BOOK_ID = BS.BOOK_ID
    AND BS.SALES_DATE >= DATE('2022-01-01')
    AND BS.SALES_DATE <= DATE('2022-01-31')
GROUP BY B.CATEGORY
ORDER BY 1;