SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
GROUP BY CATEGORY
ORDER BY 2 DESC;

# SELECT PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY = '과자'
# ORDER BY 1 DESC;