WITH BASE_TABLE AS (
    SELECT FISH_TYPE, 
        CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END AS FISH_LENGTH
    FROM FISH_INFO
)
SELECT COUNT(*) AS FISH_COUNT, MAX(FISH_LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM BASE_TABLE
GROUP BY FISH_TYPE
HAVING AVG(FISH_LENGTH) >= 33
ORDER BY 3;